In [1]:
import torch
from pathlib import Path
import pandas as pd
import numpy as np

In [32]:
emb_dim = 2
hid_sz = 400
num_layers = 3

In [33]:
vocab = ['a', 'b', 'c', 'd', 'e']
vocab_sz = len(vocab)

In [34]:
encoder = torch.nn.Embedding(vocab_sz, emb_dim)

In [36]:
lstm = torch.nn.LSTM(input_size=emb_dim, hidden_size=hid_sz, num_layers=num_layers)

In [37]:
inputs = [torch.tensor(0) , torch.tensor(1), torch.tensor(2)]

In [49]:
hidden = (torch.randn(3, 1, 400),
          torch.randn(3, 1, 400))

In [50]:
inp = torch.tensor(inputs)
emb = encoder(inp)

print(emb)
print(emb.view(len(inp), 1, -1))
out, hidden = lstm(emb.view(len(emb), 1, -1), hidden)

tensor([[-0.1003, -0.6978],
        [-1.4883,  1.6199],
        [-1.6344,  2.5097]], grad_fn=<EmbeddingBackward>)
tensor([[[-0.1003, -0.6978]],

        [[-1.4883,  1.6199]],

        [[-1.6344,  2.5097]]], grad_fn=<ViewBackward>)


In [25]:
inputs = [torch.randn(1, 3) for _ in range(5)]
inputs

[tensor([[-2.1356,  1.7282, -0.6468]]),
 tensor([[0.2478, 0.9803, 0.0129]]),
 tensor([[ 0.4120, -0.3697, -0.5888]]),
 tensor([[-1.3189,  0.0661,  0.2918]]),
 tensor([[-0.6581,  0.6158, -0.3275]])]

In [27]:
for i in inputs:
    print(i.view(1, 1, -1))
    print()

tensor([[[-2.1356,  1.7282, -0.6468]]])

tensor([[[0.2478, 0.9803, 0.0129]]])

tensor([[[ 0.4120, -0.3697, -0.5888]]])

tensor([[[-1.3189,  0.0661,  0.2918]]])

tensor([[[-0.6581,  0.6158, -0.3275]]])

